server:
  port: 8700
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://k8s04:${server.port}/eureka/,http://k8s05:${server.port}/eureka/,http://k8s06:${server.port}/eureka/

